In [1]:
import torch
import torch.nn

In [2]:
max_sequence_length = 10
d_model = 6


In [3]:
even_i = torch.arange(0, d_model, 2).float()
even_i

tensor([0., 2., 4.])

In [10]:
even_denominator = torch.pow(10000, even_i / d_model) # equation re-written for simplicity
even_denominator

tensor([  1.0000,  21.5443, 464.1590])

In [11]:
odd_i = torch.arange(1,d_model, 2).float()
odd_i

tensor([1., 3., 5.])

In [16]:
odd_denominator = torch.pow(10000, (odd_i - 1) / d_model) # equation re-written for simplicity
odd_denominator # notice that its the same as even case

tensor([  1.0000,  21.5443, 464.1590])

In [17]:
denominator = even_denominator # hence writing a single variable

In [15]:
# reshaping the positions to a 2D vector
position = torch.arange(max_sequence_length, dtype=torch.float).reshape(max_sequence_length, 1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])