In [1]:
import torch
import torch.nn

In [27]:
max_sequence_length = 2
d_model = 2


In [28]:
even_i = torch.arange(0, d_model, 2).float()
even_i

tensor([0.])

In [29]:
even_denominator = torch.pow(10000, even_i / d_model) # equation re-written for simplicity
even_denominator

tensor([1.])

In [30]:
odd_i = torch.arange(1,d_model, 2).float()
odd_i

tensor([1.])

In [31]:
odd_denominator = torch.pow(10000, (odd_i - 1) / d_model) # equation re-written for simplicity
odd_denominator # notice that its the same as even case

tensor([1.])

In [32]:
denominator = even_denominator # hence writing a single variable

In [33]:
# reshaping the positions to a 2D vector
position = torch.arange(max_sequence_length, dtype=torch.float).reshape(max_sequence_length, 1)
position

tensor([[0.],
        [1.]])

In [34]:
even_PE = torch.sin(position / denominator)
odd_PE = torch.cos(position / denominator)

In [35]:
print(even_PE)
print(odd_PE)

tensor([[0.0000],
        [0.8415]])
tensor([[1.0000],
        [0.5403]])


Interleave even and odd PE

In [36]:
stacked = torch.stack([even_PE, odd_PE], dim=2)
print(stacked.shape)
PE = torch.flatten(stacked, start_dim=2)
print(PE.shape)

torch.Size([2, 1, 2])
torch.Size([2, 1, 2])


In [37]:
print(PE)

tensor([[[0.0000, 1.0000]],

        [[0.8415, 0.5403]]])
